---
title: "Debate on Speech"
description: "Reflection on Performance and Takeaways"
author: "George Davis"
date: "10/3/25"
categories:
  - reflection
  - labreport
draft: false
---
This week, I had my debate where I opposed the notion of allowing for academic institutions to restrict patently offensive speech. I crafted my argument with my debate partner, Jacob Sesate, in two meetings prior to our debate. We coupled online research with our own logic and moral compass to guide our argument. This was partially difficult because we were slightly uncomfortable with some parts of our argument. I personally think that there should not be institution-level restrictions on speech, but there should exist social repercussions based on definitions placed by the student body. I think this is something that the honor board and the honor code accomplish well. My appreciation for what the honor code is grew during my research. Our primary argument was based on the fact that, as long as a student doesn’t threaten violence, speech should not be restricted because those bad sentiments need to be addressed and squashed before the individual enters the real world. Academic institutions are places of learning, and disallowing a student to make a mistake does not solve the issue; instead, it compresses the issue and forces the individual to resort to internet echo chambers. 
	
Unfortunately, my partner missed the debate itself due to sickness, so I had to present our points all by myself. While this was stressful, I handled myself well, and upon my reflection, it felt as if it made aspects of the debate easier. For example, I didn’t have to consider another person’s opinions when voicing my responses to questions. There were undoubtedly some things we didn’t completely agree on, and avoiding that was easy if it was only me presenting the points. I think my argument was much more congruent because it wasn’t split between two minds. In the future, I could come more prepared to the question and answer portion of these debates. I had a few drawn up before the debate, but when I got the opportunity to ask them, they felt weak. This is where having another person could have been helpful. I found the most impactful questions related to the content of their opening remarks. If I had another set of ears, I could confirm things that I didn’t completely remember them saying. 

One piece of advice I received from the professor was to try to limit my physical tics, which are a partial product of my nervousness. This is going to be difficult for me to address because it is not a part of my conscience mind. I did feel improvements from my values talk in this department, because while I was moving uncontrollably, I didn’t feel nervous. I came well prepared and was confident in my position, which helped a lot!
