---
title: "Week 2 Reflections"
description: "First Micro-ps Lab"
author: "George Davis"
date: "9/2/25"
categories:
  - reflection
  - labreport
draft: false
---

This week I completed my first micro-ps lab! This was very satisfying but difficult. I needed to brush off my surface-mount soldering and System Verilog skills quickly in order to meet the fast-approaching deadline. This was my first time using the Upduino FPGA board and the Lattice Radiant programmer to complete any task. There is always a learning curve with new software, but as I gain more experience in the computer engineering field, the curve steepens and my ability to learn quickly increases.

Looking past micro-ps, this was the first week of my senior year! I have set a goal for myself to apply for at least one job per day to give myself the best possible chances of landing something I am both passionate about and in the location I want, the Bay Area. I would be very happy to work at a company that requires me to do some HDL programming or stress the skills learned in E155. This week, I am going back home to attend my cousin’s wedding in Walla Walla, Washington. I have installed the Fusion Virtual Machine to be able to use the Lattice Radiant and Questa software for the upcoming lab. This will be a challenge, but I am confident that I am up to the task! 
