---
title: "A Lesson Taught and Claremont City Council"
description: "Halloween Week!"
author: "George Davis"
date: "10/31/25"
categories:
  - reflection
  - labreport
draft: false
---

This week, I attended a Claremont City Council meeting and led a short lesson on the idea of Joint Fact Finding (JFF) from Herman A. Karl, Lawrence E. Susskind, and Katherine H. Wallace’s A Dialogue, Not a Diatribe: Effective Integration of Science and Policy through Joint Fact Finding. Both of these events were formative for my growth as a public speaker, and I took away many lessons from each that I will discuss in this reflection. First, from the city council meeting, I observed the power that comes from representation in large numbers through a student demonstration of activism for the local unhoused community in Claremont. Second, from my joint-led lesson, I learned about the challenges that come with asking a group a leading question from a teaching standpoint and how to lead a group activity well. 

The City Council Meeting opened with remarks from the mayor and the councilmembers, including the pledge of allegiance, moments of silence for those lost, and updates about local events. This gave a sense of community and set the tone of the meeting as one of productive discussion. Next, the council opened the floor for discussion, at which point two groups became present. The first was a slightly deranged man who, among other things, threatened the city with a lawsuit on the grounds of their negligence relating to a murder that supposedly occurred in his yard. The second was a dozen or so Claremont Colleges students and an unhoused man who came to agendize the concept of keeping the public restrooms open for 24 hrs and, in general, advocating for more public funds to go towards the unhoused, or colloquially called homeless. Each member of the group took their 3 minutes to basically repeat the request of the group. This was effective at making their voices heard, as it showed how it wasn’t one person making these demands but instead a larger organization.

My lesson was centered around the concept of JFF, and my partner and I chose to approach this concept but conducting a group activity and leading a discussion afterward. I gave each student a well-thought-out role to hopefully incentivize their participation. After the activity, I opened the group up for discussion and tried to ask probing questions to get the students to understand the lesson I was attempting to teach. I learned, asking questions is hard, especially if you are trying to have someone reach a conclusion naturally and in an unbiased manner. If I were to do it again, I would have prepared a more defined method of reflection. However, my lesson went well, and the activity was well-received. Overall, this was a successful week!
