---
title: "Extemporaneous Speaking"
description: "Giving Advice to Incoming Freshman"
author: "George Davis"
date: "10/24/25"
categories:
  - reflection
  - labreport
draft: false
---
	This week in Public Speaking, I gave an impromptu speech under the prompt “What advice would you give an incoming Harvey Mudd freshman. I had one minute to prepare a hurried idea or outline of what I was intending to present to the imaginary prospective freshman class. I think this talk went well, and aspects of my delivery, especially, were surprisingly better than my other, more structured and thought-out speeches. I think the prompt was much simpler and struck a topic that I was immediately well prepared for, as opposed to my other talks, which required me to stretch for outside information. I had the opportunity to speak after two of my other classmates, which complicated my approach because I had to make sure that I wouldn’t overlap with what they were saying. Thankfully, my planned approach was very different from the talks they gave. I chose to speak about the role of the freshman year and how it impacts the rest of your college experience, which then leads you to dedicate yourself to a siloed discipline for the foreseeable future. I felt confident about this talk because it was relevant to how I was presently dealing with the looming anxiety of post-graduate life. I quickly identified freshman year as the most formative of my 4 years here at Harvey Mudd, and therefore was why I chose to speak about freshman year being a “stepping stone” between your childhood and the rest of your life. With the circumstances of this talk, I needed to develop my speech as I was telling it. I think my planning was done well and set myself up for success as I decided where I wanted to start and end the speech. The feedback I received from the professor and the class primarily related to my analytical tone and the distraction that my phone posed as my notes device. I didn’t end up ever referencing my notes and could have easily left my phone aside. This was a product of the impromptu nature of the talk, and I think having the idea of the notes nearby gave me confidence to deliver a solid talk.