---
title: "Fundamentals of Public Speaking"
description: "Values Talk Prep"
author: "George Davis"
date: "9/19/25"
categories:
  - reflection
  - labreport
draft: false
---

I enrolled late to SOSC 150 so this was my first week in the Public Speaking course. I gave myself the week to listen and learn from the other students to see what was expected from the talks. My scheduled “Values” talk is next Monday, and with what I have taken from this week, I think I am well prepared to do a good job. In this short reflection, I would like to walk through the things I noticed in the other students’ talks and how I will apply them to my own talk next week. First, I learned how the use of your inanimate objects, such as paper or digital notes, can affect a listener's attentiveness. Second, your own perceived interest in the topic you are discussing does well to draw the audience in. Finally, data to back claims up, live, bolsters your argument and will make your speech more impactful. 

Starting with note devices, I watched as some of my classmates used their notes as a sort of escape from the pressure of the eyes of the audience. On the other hand, some of my classmates only glanced at their notes when they were reciting something word-for-word or at some transition point of their speech. In essence, it was candid and natural. I tend to be slightly nervous in public speaking environments, so I will have to be wary not to fall into the trap that my peers did. One naunce that allows for a more forgiving dependence on notes is using paper notes as opposed to digital notes on a phone or tablet. 

Now moving to the idea that the audience's perception of your interest in the subject of your talk does well for their own interest. One thing Prof. Steinberg continually mentioned was that the audience will follow your lead on their opinions of your talk. If you are happy, they will be happy; if you are confident, they will be confident in your words, and unless you admit or apologize for a mistake, they probably will not notice. Some of my classmates targeted this strategy by choosing topics that they were uniquely invested in. I recall a classmate speaking about contact football in younger age groups being a positive thing. This was especially impactful to me in the audience because he explained how he played football at a young age, as had many past generations of his family. With that, I started drafting my talk based on subjects that were sourced from my own personal gripes with life. We will see where I land, but with what I have at the moment, I feel very passionate about my topics. 

Finally, whenever one of my classmates had some auxiliary facts to support their claims or a prop to hand out to the audience, if done right, I was more willing to listen to what they were arguing. Even if I did not explicitly agree with their claim, starting from a fact and then hearing their point of view in relation to that fact was helpful to understand the basis of their claim and maybe allow me to form a more charitable interpretation of their argument.
