---
title: " The Annoyances that are Subscriptions and Differed Payment Services"
description: "Reflection on Performance and Takeaways on my Talk"
author: "George Davis"
date: "9/26/25"
categories:
  - reflection
  - labreport
draft: false
---
This week I gave my first talk to the class! The subject of the talk was based on a set of my own personal values relating to any experience or widespread argument. I chose to speak about my belief that we as individuals are being forced to enter short-term and unnecessary financial agreements with corporations to chase a mirage of choice that we have identified to be present in upper-class circles. I was really excited about my topic because not only did I feel comfortable speaking on it, I felt it was a profound issue in our present society that was not spoken about all too often. I related my gripe to two main instances of these short term financial contracts present to any American consumer: subscription services and the option to finance single to double digit purchases over a few months. My main point was that while each of these financial tools may seem to allow the consumer more freedom they actually restrict your options and only give you the illusion of choice. For example within a subscription based streaming service maybe ten percent of the content is watchable while the rest is merely filler. With the deferred payment or financing tool you are signing away a portion of your income for the next few months to a small purchase. This stacked up over many purchases would be incredibly damaging to your financial consistency. One is incentivized to use this tool even though it places a long term financial burden on them because they desire to live above their means and experience something at a time of their choosing without thinking about the financial consequences as a rich person might. 

I found through giving my speech that my argument as explained above is much more clear and easy to understand in a written format and is weakened when I am asked to vocalize it. The main point of feedback I received that I need to incorporate in the future was that in order to make sure that your audience understands your argument at all points you need to reiterate the central thesis throughout the speech. Most of my formal argumentative analysis training has been through written essays or papers so this shift in structure is new to me. I am confident that I will be able to incorporate this feedback into my future talks as it is as simple as restating the thesis periodically after new information has been provided. The second piece of advice I received from the class and professor was that my nervousness was noticeable but only present in my shaking hands. This was a quick tell to my listeners that I was uncomfortable and anxious. I have found that when the speaker displays emotion the listeners will follow them. I will have to work out a way to stop my hands shaking, or at least make it less noticeable to mitigate this. 
